services:
  proxy:
    image: nginx:1.23.3-alpine
    container_name: app-map-proxy
    restart: always
    ports: 
      - 80:80      
      - 443:443    
    volumes:
      - ./web.conf:/etc/nginx/conf.d/web.conf
      # Volumes pour les certificats SSL Let's Encrypt
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
    - app-map-network

networks:
  app-map-network:
    external: true
    name: app-map-network

