# unused ( pas de db pour le moment)
server {
    server_name     db.app-map.knop.fr

    location / {
        # TODO: comprendre l'url du proxy
        proxy_pass      http://app-map-db:8080;
    }
}