server {
    # ttes les requetes pertent du serveur , pas de dns secondaire
    server_name     vps-954b32b8.vps.ovh.net

    location / {
        proxy_pass      http://app-map-front;
    }

    location /api {
        proxy_pass      http://app-map-back:8080;
    }
}