# Redirection HTTP vers HTTPS
server {
    listen 80;
    server_name vps-954b32b8.vps.ovh.net;
    
    # Endpoint pour la validation du certificat Let's Encrypt ( preuve de possession du dns)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    # Rediriger tout le reste vers HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# Configuration HTTPS principale
server {
    listen 443 ssl http2;
    server_name vps-954b32b8.vps.ovh.net;

    ssl_certificate /etc/letsencrypt/live/vps-954b32b8.vps.ovh.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vps-954b32b8.vps.ovh.net/privkey.pem;
    
    # Paramètres SSL recommandés pour la sécurité
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';

    # Route vers le frontend
    #location / {
    #    proxy_pass http://app-map-front;
    #    proxy_set_header Host $host;
    #    proxy_set_header X-Real-IP $remote_addr;
    #    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #    proxy_set_header X-Forwarded-Proto $scheme;
    #}

    # Route vers le backend API (pour web et mobile)
    location /api {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://app-map-back:8080;
    }
}