name: deploy app-map proxy
on: [push]
env: 
  IMAGE: app-map-proxy
  VERSION: 0.1.0
jobs:
  create-folder:
    name: create folder
    runs-on: ubuntu-latest
    steps:
      - name: execute commands
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            sudo mkdir -p /opt/applications/app-map/${{ env.IMAGE }}
            sudo chown -R $USER:$USER /opt/applications/app-map/${{ env.IMAGE }}
            ls -al /opt/applications/app-map
  
  run-container: 
    name: run container
    runs-on: ubuntu-latest
    needs: ['create-folder']
    steps: 
      - name: cloner le repertoire
        uses: actions/checkout@main
      - name: copy file via ssh key
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "compose.yml,web.conf"
          target: /opt/applications/app-map/${{env.IMAGE}}
      - name: execute commands to run container
        uses: appleboy/ssh-action@v1.2.3
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker network create app-map-network || true
            sudo docker compose -f /opt/applications/app-map/${{env.IMAGE}}/compose.yml up -d